name: on PR CI

on:
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Test mocha
    runs-on: [macOS-10.14]
    steps:
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0
      - name: Npm test in project
        run: npm run test
